### ISSUE TITLE
ValueError: Harmonization failed with method reduce_ratio_2080  harmonized  values != historical values

### ISSUE THREAD

**Issue by hljia** [iiasa/aneris#48] opened 2022-04-19 09:06 UTC
I am now trying to harmony SSP emissions to the new version CEDS v_2021_04_21 historical emissions with a base year of 2019. When I used the test data, the aneris run smoothly. But when I replaced the test data by real annual BC emission over U.S. from CEDS and SSP245 (aneris ssp245_EU_BC.xls --history history_EU_BC.xls --regions regions_mapping_unused.csv --rc aneris_regions_sectors.yaml), the following error occurred:

> INFO:root:Downselecting prefix|suffix variables
> INFO:root:Translating to standard format
> INFO:root:Aggregating historical values to native regions
> WARNING:root:Removing regions without direct mapping: ['EU']
> INFO:root:Harmonizing (with example methods):
> INFO:root:region  gas  sector                 units
> World   BC   prefix|sector1|suffix  kt       reduce_ratio_2080
> Name: method, dtype: object
> INFO:root:Harmonizing with reduce_ratio_2080
> Traceback (most recent call last):
>   File "/home/b/b381315/.conda/envs/hjia/bin/aneris", line 33, in <module>
>     sys.exit(load_entry_point('aneris-iamc==0.3.0', 'console_scripts', 'aneris')())
>   File "/home/b/b381315/.conda/envs/hjia/lib/python3.9/site-packages/aneris/cli.py", line 90, in main
>     harmonize(args.input_file, args.history, args.regions,
>   File "/home/b/b381315/.conda/envs/hjia/lib/python3.9/site-packages/aneris/cli.py", line 64, in harmonize
>     driver.harmonize(scenario)
>   File "/home/b/b381315/.conda/envs/hjia/lib/python3.9/site-packages/aneris/harmonize.py", line 489, in harmonize
>     self._model, self._meta = _harmonize_regions(
>   File "/home/b/b381315/.conda/envs/hjia/lib/python3.9/site-packages/aneris/harmonize.py", line 619, in _harmonize_regions
>     model = harmonizer.harmonize(overrides=overrides)
>   File "/home/b/b381315/.conda/envs/hjia/lib/python3.9/site-packages/aneris/harmonize.py", line 261, in harmonize
>     raise ValueError(msg.format(method, report))
> ValueError: Harmonization failed with method reduce_ratio_2080 harmonized                     values != historical values. This is likely due to an                     override in the following variables:
> 
>   region gas                 sector units          2019
> 0  World  BC  prefix|sector1|suffix    kt  53369.230769

I searched on the offical website and github of aneris, but couldn't find a solution. The input data are also attached (data_aneris.zip). Many thanks!

[data_aneris.zip](https://github.com/iiasa/aneris/files/8511485/data_aneris.zip)

**Comment by gidden** [comment] 2022-04-19 19:23
Hi @hljia - thanks for creating this issue! At first glance from the output and files you provided, it seems that the mapping of regions provided to `aneris` does not match with the historical and model data. 

Specifically, you need to develop a mapping file that maps the `ISO Code` in your historical data to the `Native Region` values of your modelled data.

I also can not seem to open the relevant history and model data files (they have no extension).

**Comment by hljia** [comment] 2022-04-20 08:33
Hi @gidden,

Many thanks for you reply! I tried to modify the mapping file as following, but unfortunately it doesn't work also with the same error.

> ISO Code,Country,Native Region Code,5_region
EU,EU,EU,EU
World,World,World,World

 I am now attaching  history and model data files for your information.
[history_EU_BC.xls](https://github.com/iiasa/aneris/files/8519680/history_EU_BC.xls)
[ssp245_EU_BC.xls](https://github.com/iiasa/aneris/files/8519681/ssp245_EU_BC.xls)

**Comment by gidden** [comment] 2022-04-20 09:44
Hi @hljia - I was not able to reproduce the specific error you report here, but after investigating your example data, I was able to produce harmonized results with the attached data set (`regions.csv` and `rc.yaml` have been updated, other files are as you provided) and the below command

```
$ aneris --history history_EU_BC.xls --regions regions.csv --rc rc.yaml ssp245_EU_BC.xls
```
[test-aneris.zip](https://github.com/iiasa/aneris/files/8520342/test-aneris.zip)

**Comment by gidden** [comment] 2022-04-20 09:44
If you can confirm, feel free to close this issue, please!

**Closed** 2022-04-20 14:39 UTC
